config/routes.rb
Rails.application.routes.draw do
  
  get 'result/result/:id' => "result#result"

  get 'choice/result'
  
  get 'infos/school'

  get 'scafds/new/:score' => "scafds#new"
  
  post 'scafds/create'
  
  get 'choice/first'

  get 'choice/second/:score' => 'choice#second'

  get 'choice/third/:score' => 'choice#third'

  get 'choice/four/:score' => 'choice#four'

  get 'choice/five/:score' => 'choice#five' 

  root 'infos#index'
  
  get 'infos/index'
  
  get '/infos/greats'

  get '/infos/lauren'
  
  get '/infos/mark'
  
  get '/infos/oracle'
  
  get '/infos/paul'
  
  get '/infos/stevejobs'
  
  get '/infos/amancio'
  
  get '/infos/billgates'
  
  get '/infos/dell'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/scafd.rb
class Scafd < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
  def first
  end
  
  def second
      @score = params[:score]
  end
  
  def third
      @score = params[:score]
  end
  
  def four
      @score = params[:score]
  end
  
  def five
      @score = params[:score]
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @choice_url = '../choice/first.html/'
  end
  def greats
  end
  def lauren
  end
  def mark
  end
  def oracle
  end
  def paul
  end
  def 
  def stevejobs
  end
  def amacino
  end
  def billgates
  end
  def dell
  end
end

app/controllers/result_controller.rb
require 'net/http'
class ResultController < ApplicationController
  def result
    @user = Scafd.find(params[:id])
    if @user.score.to_i <= 5
      @reslut = 10
      @content_title = "그냥 학교 다니자"
      @content_sub = "교수하는건 어때?"
    elsif @user.score.to_i == 15
      @reslut = 100
      @content_title = "무조건, 무조건 	자퇴!"
      @content_sub = "당신은 자퇴와 소울 메이트입니다. 하루 빨리 자퇴하세요."
    elsif @user.score.to_i > 10
      @reslut = 70
      @content_title = "자퇴각이 보이네"
      @content_sub = "인생 한번쯤 자퇴해도 괜찮을듯?"
    else
      @reslut = 40
      @content_title ="자퇴하기는 애매한데,,"
      @content_sub ="당신은 휴학이 적당한거 같네"
    end
    # NOTE: You must use the same region in your REST call as you used to obtain your subscription keys.
    #   For example, if you obtained your subscription keys from westus, replace "westcentralus" in the
    #   URL below with "westus".
    uri = URI('https://westcentralus.api.cognitive.microsoft.com/face/v1.0/detect')
    uri.query = URI.encode_www_form({
       'returnFaceId' => 'true',
      'returnFaceLandmarks' => 'false',
      'returnFaceAttributes' => 'age,gender,smile',
    })
    
    request = Net::HTTP::Post.new(uri.request_uri)
    # Request headers
    request['Content-Type'] = 'application/json'
    # NOTE: Replace the "Ocp-Apim-Subscription-Key" value with a valid subscription key.
    request['Ocp-Apim-Subscription-Key'] = 'c3862170741d4a8395d92b7f5b2fbab9'
    # Request body
    request.body = "{\"url\":\"https://newbeeton-yung94.c9users.io"+ @user.image.to_s + "\"}"
    
    response = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
        http.request(request)
    end

    puts response.body
    ha = JSON.parse(response.body)
    faceattributes = ha.first["faceAttributes"]
    @emotion = faceattributes["smile"].to_f
    @gender = faceattributes["gender"]
    @age = faceattributes["age"]
  end
end

app/controllers/scafds_controller.rb
require 'carrierwave/orm/activerecord'
class ScafdsController < ApplicationController
  before_action :set_scafd, only: [:show, :edit, :update, :destroy]

  # GET /scafds
  # GET /scafds.json
  def index
    @scafds = Scafd.all
  end

  # GET /scafds/1
  # GET /scafds/1.json
  def show
  end

  # GET /scafds/new
  def new
    @scafd = Scafd.new
    @score = params[:score]
  end

  # GET /scafds/1/edit
  def edit
  end

  # POST /scafds
  # POST /scafds.json
  def create
    @scafd = Scafd.new
    @scafd.user_name = params[:user_name]
    @scafd.univ = params[:univ]
    @scafd.birth = params[:birth]
    @scafd.major = params[:major]
    @scafd.image = params[:image]
    @scafd.score = params[:score]

    respond_to do |format|
      if @scafd.save
        format.html { redirect_to "/result/result/#{@scafd.id}", notice: 'Scafd was successfully created.' }
        format.json { render :show, status: :created, location: @scafd }
      else
        format.html { render :new }
        format.json { render json: @scafd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scafds/1
  # PATCH/PUT /scafds/1.json
  def update
    respond_to do |format|
      if @scafd.update(scafd_params)
        format.html { redirect_to @scafd, notice: 'Scafd was successfully updated.' }
        format.json { render :show, status: :ok, location: @scafd }
      else
        format.html { render :edit }
        format.json { render json: @scafd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scafds/1
  # DELETE /scafds/1.json
  def destroy
    @scafd.destroy
    respond_to do |format|
      format.html { redirect_to scafds_url, notice: 'Scafd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scafd
      @scafd = Scafd.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/scafds_helper.rb
module ScafdsHelper
end

app/views/choice/first.html.erb
<div id="left">
		<p id="qust_one">Question 1/5</p>
		<hr width="30%" color="#e91e63">

		<img id="img_first" src="https://pbs.twimg.com/profile_images/715935653175754752/siZJedFG_400x400.jpg">

		<p id="quse_one_content">월요일만 되면 왜 살까 진지하게 고민한다.</p>

		<p id="circle" class="c_1"></p>
		<p id="circle" class="c_2"></p>
		<p id="circle" class="c_3"></p>
		<p id="circle" class="c_4"></p>
		<p id="circle" class="c_5"></p>

	</div>

	<img id="tri" src="/assets/triangle.png">

	<div id="right">
			<p id="select_content">Select Answer Below</p>

			<hr id="answer_hr" width="30%" color="#ffffff">
			<a href="/choice/second/3"><button> <span> A </span>그렇다</button></a>
			<hr id="hr_1" width="70%" color="#ffffff">
			<a href="/choice/second/2"><button> <span> B </span>보통이다</button></a>
			<hr id="hr_1" width="70%" color="#ffffff">
			<a href="/choice/second/0"><button> <span> C </span>아니다</button> </a>
			<hr id="hr_1" width="70%" color="#ffffff">
			<a href="/choice/second/1"><button> <span> D </span>모르겠다</button></a>
			<hr id="hr_1" width="70%" color="#ffffff">
		
	</div>
	
	<style>
		
		body{
			font-family: 'NanumSquareB';
	margin: 0px;
	background-color: #ec3e79;
}

#left{
	position: absolute;
	height: 653px;
	width: 50%;
	background-color: white;
	text-align: center;
}

#right{
	width: 50%;
	height: 653px;
	position: absolute;
	margin-left: 50%;
	text-align: center;
}

p{
	margin: 0px;
}


#tri{
	width: 30px;
	height: 50px;
	position: absolute;
	margin-left: 49%;
	margin-top: 6%;
}

#qust_one{
	font-size: 25px;
	margin-top: 10%;
	margin-bottom: 3%;
	font-weight: bold;
	color: #e91e63;
}

#img_first{
	margin-top: 8%;
	width: 250px;
	height: 250px;
	border: 2px #e91e63 solid;
	-webkit-border-radius: 200px;
}

#quse_one_content{
	margin-top: 8%;
	font-size: 30px;
	font-weight: bold;
	color: black;
}

#select_content{
	font-size: 25px;
	margin-top: 10%;
	padding-bottom: 3%;
	font-weight: bold;
	color: white;
}

#choice{
	margin-top: 5%;
	font-size: 25px;
	color: white;
}

button{
	text-align: left;
	background:#ec3e79;
	color:#fff;
	border:none;
	position:relative;
	height: 80px;
	width: 70%;
	font-size:1em;
	padding:0 2em;
	cursor:pointer;
	transition:800ms ease all;
	outline:none;
	border-radius: 5px;
}
button:hover{
	background:#fff;
	color: #ec1f64;
}
button:before,button:after{
	content:'';
	position:absolute;
	top:0;
	right:0;
	height:2px;
	width:0;
	background: #ec1f64;
	transition:400ms ease all;
}
button:after{
	right:inherit;
	top:inherit;
	left:0;
	bottom:0;
}
button:hover:before,button:hover:after{
	width:100%;
	transition:800ms ease all;
}

#hr_1{
	margin-top: 0px;
	margin-bottom: 5%;
}

#answer_hr{
	margin-top: 1%;
	margin-bottom: 5%;
}

#circle{
	margin-left: 2%;
	margin-right: 2%;
	margin-top: 10%;
	display: inline-block;
	width: 10px;
	height: 10px;
	-webkit-border-radius: 100px;
	-moz-border-radius: 100px;
}

.c_1{
	background-color: #e91e63;
}

.c_2, .c_3, .c_4, .c_5{
	background-color: #e1e1e1;
}

span{
	margin-right: 35%;
	margin-left: 5%;
}
	</style>

app/views/choice/five.html.erb
<div id="left">
		<p id="qust_one">Question 5/5</p>
		<hr width="30%" color="#e91e63">

		<img id="img_first" src="http://ppss.kr/wp-content/uploads/2017/07/5-30.jpg">

		<p id="quse_one_content">학점을 보다 보면 한숨만 나온다.</p>

		<p id="circle" class="c_2"></p>
		<p id="circle" class="c_3"></p>
		<p id="circle" class="c_4"></p>
		<p id="circle" class="c_5"></p>
		<p id="circle" class="c_1"></p>

	</div>

	<img id="tri" src="/assets/triangle.png">

	<div id="right">
		<p id="select_content">Select Answer Below</p>

		<hr id="answer_hr" width="30%" color="#ffffff">
		<a href="/scafds/new/<%= @score.to_i + 3 %>"><button> <span> A </span>그렇다</button></a>
		<hr id="hr_1" width="70%" color="#ffffff">
		<a href="/scafds/new/<%= @score.to_i + 2 %>"><button> <span> B </span>보통이다</button></a>
		<hr id="hr_1" width="70%" color="#ffffff">
		<a href="/scafds/new/<%= @score.to_i + 0 %>"><button> <span> C </span>아니다</button></a>
		<hr id="hr_1" width="70%" color="#ffffff">
		<a href="/scafds/new/<%= @score.to_i + 1 %>"><button> <span> D </span>모르겠다</button></a>
		<hr id="hr_1" width="70%" color="#ffffff">
	</div>
	
	<style>
		
		body{
	margin: 0px;
	background-color: #ec3e79;
	font-family: 'NanumSquareB';
}

#left{
	position: absolute;
	height: 653px;
	width: 50%;
	background-color: white;
	text-align: center;
}

#right{
	width: 50%;
	height: 653px;
	position: absolute;
	margin-left: 50%;
	text-align: center;
}

p{
	margin: 0px;
}


#tri{
	width: 30px;
	height: 50px;
	position: absolute;
	margin-left: 49%;
	margin-top: 6%;
}

#qust_one{
	font-size: 25px;
	margin-top: 10%;
	margin-bottom: 3%;
	font-weight: bold;
	color: #e91e63;
}

#img_first{
	margin-top: 8%;
	width: 250px;
	height: 250px;
	border: 2px #e91e63 solid;
	-webkit-border-radius: 200px;
}

#quse_one_content{
	margin-top: 8%;
	font-size: 30px;
	font-weight: bold;
	color: black;
}

#select_content{
	font-size: 25px;
	margin-top: 10%;
	padding-bottom: 3%;
	font-weight: bold;
	color: white;
}

#choice{
	margin-top: 5%;
	font-size: 25px;
	color: white;
}

button{
	text-align: left;
	background:#ec3e79;
	color:#fff;
	border:none;
	position:relative;
	height: 80px;
	width: 70%;
	font-size:1em;
	padding:0 2em;
	cursor:pointer;
	transition:800ms ease all;
	outline:none;
	border-radius: 5px;
}
button:hover{
	background:#fff;
	color: #ec1f64;
}
button:before,button:after{
	content:'';
	position:absolute;
	top:0;
	right:0;
	height:2px;
	width:0;
	background: #ec1f64;
	transition:400ms ease all;
}
button:after{
	right:inherit;
	top:inherit;
	left:0;
	bottom:0;
}
button:hover:before,button:hover:after{
	width:100%;
	transition:800ms ease all;
}

#hr_1{
	margin-top: 0px;
	margin-bottom: 5%;
}

#answer_hr{
	margin-top: 1%;
	margin-bottom: 5%;
}

#circle{
	margin-left: 2%;
	margin-right: 2%;
	margin-top: 10%;
	display: inline-block;
	width: 10px;
	height: 10px;
	-webkit-border-radius: 100px;
	-moz-border-radius: 100px;
}

.c_1{
	background-color: #e91e63;
}

.c_2, .c_3, .c_4, .c_5{
	background-color: #e1e1e1;
}

span{
	margin-right: 35%;
	margin-left: 5%;
}
	</style>

app/views/infos/greats.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
           
   
    <title>Document</title>
    <style>
        svg {
            height: 100%;
            width: 100%;
                                                                                                                                       
        }
        g {
            height: 100%;
            width: 100%;
        }
        img {
            height: 40 %;
            width: 24%;
            
        }
        h3{
            
        }
    </style>
</head>
<body>
   <a href="/infos/stevejobs"><img src="/assets/steve_.png" alt="image"></a>
   <a href="/infos/billgates"><img src="/assets/bill_.png" ></a>
   <a href="/infos/paul"><img src="/assets/paul_.png" ></a>
   <a href="/infos/mark"><img src="/assets/mark_.png" ></a>
   <a href="/infos/lauren"><img src="/assets/lauren_.png" ></a>
   <a href="/infos/dell"><img src="/assets/dell_.png" ></a>
   <a href="/infos/amancio"><img src="/assets/amancio_.png" ></a>
   <a href="/infos/oracle"><img src="/assets/larry_.png" > </a>
</body>
    
</html>

app/views/scafds/_form.html.erb
<head>
  <style>
  .dropdown {
         position: relative;
      display: inline-block;
      float: right;
  
  }
  
  A:link, A:visited { 
  text-decoration:none; 
  
  }
  
  
  .dropdown-content {
            text-align: right;
      display: none;
      position: absolute;
      background-color: #ebba16;
      border-radius: 30px;
      min-width: 300px;
      height: 35px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
      margin-top: 28px;
     margin-left: -313px;
  }
  
  .dropdown:hover .dropdown-content {
      display: block;
       
  
  }
  
  .desc {
      padding: 15px;
      text-align: center;
          font-size: 15px;
          margin-top: -7px;
  
  }
  
  body {
   font-family:'NanumSquareB';
   margin: 0;
  	}
  
  .left-box {
    background: white;
    float: left;
    width: 50%;
    height: 720px;
    background:url('bg.png');
    background-position:center;
  
   
  }
  .left-box:hover{
   background:url('bg2.png');
   background-position:center;
  }
  
  .right-box {
    background: #81c684;
    float: right;
    width: 50%;
    height: 720px;
  }
  
  .menu {
  	width : 50px;
  	height: 50px;
  	float: right;
  	margin-top: 20px;
  	margin-right: 20px;
  	
  }
  
  
  
  .title{
  	margin-top: 100px;
  	text-align: center;
  	font-size: 20px;
  	color :white;
  }
  
  .s:hover{
    opacity: 0.7;
  }
  
  .s{
  	
  display:block;
  margin:0 auto; 
  border-radius: 100px;
  }
  
  .subtitle{
    text-align: center;
    font-size: 50px;
  }
  
  .subject{
     text-align: center;
     font-size: 20px;
  }
  
  .subject2{
     text-align: center;
     font-size: 11px;
     line-height: 23px;
     letter-spacing: 0.5px;
  }
  
  
  
  .crown{
  	display:block;
  margin:0 auto; 
  width: 50px;
  height: 50px;
  }
  
  
  
  html{
    height:100%;
  }
  body{
    text-align:center;
  
  
  }
 
  button{
    background:#1AAB8A;
    color:#fff;
    border:none;
    position:relative;
    height:60px;
    font-size:1.6em;
    padding:0 2em;
    cursor:pointer;
    transition:800ms ease all;
    outline:none;
  }
  button:hover{
    background:#fff;
    color:#1AAB8A;
  }
  button:before,button:after{
    content:'';
    position:absolute;
    top:0;
    right:0;
    height:2px;
    width:0;
    background: #1AAB8A;
    transition:400ms ease all;
  }
  button:after{
    right:inherit;
    top:inherit;
    left:0;
    bottom:0;
  }
  button:hover:before,button:hover:after{
    width:100%;
    transition:800ms ease all;
  }
  
  button.af{
    background:#1AAB8A;
    color:#fff;
    border:none;
    position:relative;
    height:60px;
    font-size:1.6em;
    padding:0 2em;
    cursor:pointer;
    transition:800ms ease all;
    outline:none;
  }
  button.af:hover{
    background:#fff;
    color:#1AAB8A;
  }
  button.af:before,button:after{
    content:'';
    position:absolute;
    top:0;
    right:0;
    height:2px;
    width:0;
    background: #1AAB8A;
    transition:400ms ease all;
  }
  button.af:after{
    right:inherit;
    top:inherit;
    left:0;
    bottom:0;
  }
  button.af:hover:before,button.af:hover:after{
    width:100%;
    transition:800ms ease all;
  }

    body{
  	margin: 0px;

  }
  
  #left{
  	position: absolute;
  	height: 670px;
  	width: 50%;
  	background-color: white;
  	text-align: center;
  }
  
  #right{
  	width: 50%;
  	height: 653px;
  	position: absolute;
  	margin-left: 50%;
  	text-align: center;
  }
  
  p{
  	margin: 0px;
  }
  
  #tri{
  	width: 30px;
  	height: 50px;
  	position: absolute;
  	margin-left: -0.3%;
  	margin-top: 6%;
  }
  
  #qust_one{
  	font-size: 25px;
  	margin-top: 10%;
  	margin-bottom: 3%;
  	font-weight: bold;
  	color: #ffffff;
  }
  
  #img_first{
  	margin-top: 8%;
  	width: 300px;
  	height: 300px;
  	border: 2px #ffffff solid;
  	-webkit-border-radius: 200px;
  }
  
  #quse_one_content{
  	margin-top: 8%;
  	font-size: 30px;
  	font-weight: bold;
  	color: white;
  }
  
  #choice{
  	margin-top: 5%;
  	font-size: 25px;
  	color: white;
  }
  
  #hr_1{
  	margin-top: 0px;
  	margin-bottom: 5%;
  }
  
  #answer_hr{
  	margin-top: 1%;
  	margin-bottom: 5%;
  }
  
  #circle{
  	margin-left: 2%;
  	margin-right: 2%;
  	margin-top: 10%;
  	display: inline-block;
  	width: 10px;
  	height: 10px;
  	-webkit-border-radius: 100px;
  	-moz-border-radius: 100px;
  }
  
  .c_1{
  	background-color: #e91e63;
  }
  
  .c_2, .c_3, .c_4, .c_5{
  	background-color: #e1e1e1;
  }
  
  span{
  	margin-right: 35%;
  	margin-left: 5%;
  }
  
  .menu {
     width : 50px;
     height: 50px;
     float: right;
     margin-top: 20px;
     margin-right: 20px;   
  }
  
  #main_content{
  	font-size: 25px;
  	margin-top: 10%;
  	margin-right: 3%;
  	padding-bottom: 3%;
  	font-weight: bold;
  	color: black;
  }
  
  input.img1{
  height:150px;
  }
  
  #persent{
  	font-size: 50px;
  	font-weight: bold;
  	margin-top: 15%;
  }
  
  #sub_title{
  	margin-top: 5%;
  	font-size: 17px;
  	font-weight: bold;
  	text-align: left;
  	margin-left: 16%;
  	line-height: 40px;
  }
  
  #sub_content{
  	margin-top: 3%;
  	font-size: 15px;
  }
  
  button{
  	text-align: center;
  	background:#f1a93f;
  	color:#fff;
  	border:none;
  	position:relative;
  	height: 50px;
  	width: 30%;
  	font-size:1em;
  	padding:0 2em;
  	cursor:pointer;
  	transition:800ms ease all;
  	outline:none;
  	border-radius: 5px;
  	margin-top: 10%;
  	margin-left: 3%;
  	margin-right: 3%;
  }
  button:hover{
  	background:#fff;
  	color: gray;
  }
  button:before,button:after{
  	content:'';
  	position:absolute;
  	top:0;
  	right:0;
  	height:2px;
  	width:0;
  	background: gray;
  	transition:400ms ease all;
  }
  button:after{
  	right:inherit;
  	top:inherit;
  	left:0;
  	bottom:0;
  }
  button:hover:before,button:hover:after{
  	width:100%;
  	transition:800ms ease all;
  }

</style>    
</head>
<body style="background-color: #f1a93f;">

  <%= form_tag scafds_create_path, multipart: true do %>
	<div id="left">
		<p id="main_content">자퇴테스트</p>
		<hr id="answer_hr" width="33%" color="black">
	  <input type="hidden" name = "score" value="<%= @score %>">
		<p id="sub_title">
		  자신이 자퇴했을 때 모습이 나타나는 얼굴사진을 올리세요<br>
			사진 <%= file_field_tag :image %>
			<br>
			이름 <input type="text" name="user_name">		<br>	생년월일  <select class="" name="">
      <option value="">2000</option>
      <option value="">1999</option>
      <option value="">1998</option>
      <option value="">1997</option>
      <option value="">1996</option>
      <option value="">1995</option>
      <option value="">1994</option>
      <option value="">1993</option>
      <option value="">1992</option>
      <option value="">1991</option>
      <option value="">1990</option>
      </select> 년
      <select class="" name="">
      <option value="">1</option>
      <option value="">2</option>
      <option value="">3</option>
      <option value="">4</option>
      <option value="">5</option>
      <option value="">6</option>
      <option value="">7</option>
      <option value="">8</option>
      <option value="">9</option>
      <option value="">10</option>
      <option value="">11</option>
      <option value="">12</option>
      </select> 월
       <select class="" name="">
      <option value="">1</option>
      <option value="">2</option>
      <option value="">3</option>
      <option value="">4</option>
      <option value="">5</option>
      <option value="">6</option>
      <option value="">7</option>
      <option value="">8</option>
      <option value="">9</option>
      <option value="">10</option>
      <option value="">11</option>
      <option value="">12</option>
      <option value="">13</option>
      <option value="">14</option>
      <option value="">15</option>
      <option value="">16</option>
      <option value="">17</option>
      <option value="">18</option>
      <option value="">19</option>
      <option value="">20</option>
      <option value="">21</option>
      <option value="">22</option>
      <option value="">23</option>
      <option value="">24</option>
      <option value="">25</option>
      <option value="">26</option>
      <option value="">27</option>
      <option value="">28</option>
      <option value="">29</option>
      <option value="">30</option>
      <option value="">31</option>
      </select> 일<br> 
			대학교 <select name="univ" size=1 multiple><option>강원대</option>
		<option>국민대</option>
		<option>서울시립대</option>
		<option>동국대</option>
		<option>덕성여대</option> 
		<option>성결대</option>
		<option>아주대</option>
		<option>한국외대</option>
		<option>성신여대</option>
		<option>아주대</option>
		<option>남서울대</option>
		<option>경기대</option>
		</select><br>
			학과 <input type="text" name="major" value="학과">


		</p>

		<button>CREDIT</button>
		<% end %>
	</div>

	<img id="tri" src="/assets/triangle.png">

	<div id="right">
		<p id="qust_one">ㅠㅠ</p>
		<hr width="30%" color="#ffffff">

		<img id="img_first" src="https://pbs.twimg.com/profile_images/715935653175754752/siZJedFG_400x400.jpg">

		<p id="quse_one_content">나는 누구죠?</p>
	</div>

	
</body>

app/views/scafds/edit.html.erb
<!--<h1>Editing Scafd</h1>-->

<!--<%= render 'form', scafd: @scafd %>-->

<!--<%= link_to 'Show', @scafd %> |-->
<!--<%= link_to 'Back', scafds_path %>-->

app/views/scafds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scafds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scafds.each do |scafd| %>
      <tr>
        <td><%= scafd.user_name %></td>
        <td><%= image_tag(scafd.image.url, class: "indexing") %></td>
        <td><%= link_to 'Show', scafd %></td>
        <td><%= link_to 'Edit', edit_scafd_path(scafd) %></td>
        <td><%= link_to 'Destroy', scafd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scafd', new_scafd_path %>

app/views/scafds/show.html.erb
<p id="notice"><%= notice %></p>


<div> <!--leftbox-->
  <%= image_tag(@scafd.image.url) %>
</div>

<div> <!--rightbox-->
  <p>Name</p>
  <%= @scafd.user_name %>
  
  <p>Birth</p>
  <%= @scafd.birth %>
  
  <p>University</p>
  <%= @scafd.univ %>
  
  <p>Major</p>
  <%= @scafd.major %>
</div>


<%= link_to 'Edit', edit_scafd_path(@scafd) %> |
<%= link_to 'Back', scafds_path %>